// export const GET_USER_BY_USERID_REQUEST = 'GET_USER_BY_USERID_REQUEST'
// export const GET_USER_BY_USERID_SUCCESS = 'GET_USER_BY_USERID_SUCCESS'
// export const GET_USER_BY_USERID_FAILURE = 'GET_USER_BY_USERID_FAILURE'

export const SET_AUTHORIZATION = 'SET_AUTHORIZATION'
export const TEST_REDUX_CHANGE = 'TEST_REDUX_CHANGE'
